name: "k8s_secret_decoder"
description: "Decode base64 secrets from Kubernetes Secret data section"
version: "1.0"

transformations:
  - type: "function_based"
    config:
      template: |
        {{ input 
           | split_lines 
           | map_values(base64_decode) 
           | join_lines }}

      allowed_functions:
        - split_lines
        - map_values
        - base64_decode
        - join_lines

      line_range:
        start_pattern: "^data:"
        stop_pattern: "^(metadata|spec|status|kind):"
        include_boundaries: false
